# Generated by Django 6.0.5 on 2026-05-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CORRECTION_NEEDED', 'Correction Needed'), ('STATUS_UPDATE', 'Status Update')], default='INFO', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
