# Generated by Django 6.0.5 on 2026-05-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness_score', models.FloatField()),
                ('consistency_score', models.FloatField()),
                ('quality_score', models.FloatField()),
                ('identity_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
